const en = {
  "welcome-to-invite": "Welcome to invite",
  "join-the-inviter": "Join the inviter",
  "do-you-have-account": "Do you have account",
  "sign-in": "Sign In",
  "create-an-account-to-invite": "Create an account in invited",
  "full-name": "fullname",
  or: "or",
  email: "Email",
  phone: "Mobile No",
  password: "Password",
  cpassword: "Confirm Password",
  "create-an-account": "Register",
  back: "Back",
  "mobile-number-activation": "Mobile number activation",
  "to-complete-the-activation-process-please-enter-the-code":
    "To complete the activation process, please enter the code",
  "activate-account": "Activate account",
  "resend-the-code": "Resend",
  "enter-mobile-or-email": "Enter mobile or email",
  "pass-head": "Password",
  "forget-your-password": "Forget your password",
  "enter-the-register-email": "Enter the register Email",
  submit: "Submit",
  "enter-the-token-you-receives": "Enter the token you receives",
  "new-password": "New Password",
  "design-customize": "Design customize",
  "customize-description":
    "You can choose a design from the invited designs, and update the type, colors and sizes of the fonts",
  "follow-up-on-invitees": "Follow up on invitees",
  "you-can-follow-up-on-the-invitees-and-know-who-has-confirmed-their-attendance-excused-or-not-answered-the-invitation-and-other-attendance-statuses":
    "You can follow up on the invitees and know who has confirmed their attendance excused or not answered the invitation and other attendance statuses",
  "special-design-request": "Special design request",
  "with-the-help-of-invited-designers-you-can-stand-out-by-requesting-only-your-own-design":
    "With the help of invited designers, you can stand out by requesting only your own design",
  "start-to-invite": "Start to invite",
  invitation: "Invitation",
  everyone: "Everyone",
  efective: "Effective",
  archive: "Archive",
  ended: "Ended",
  ongoing: "Ongoing",
  "browse-design": "Browse design",
  for: "for",
  modification: "تعديل",
  type: "النوع",
  "family-font": "الحجم",
  color: "اللون",
  align: "التنسيق",
  filter: "تصفية",
  "age-group": "الفئة العمرية",
  children: "اطفال",
  youth: "شباب",
  adult: "بالغين",
  "card-with-number": "كرت مع رقم",
  no: "لا",
  yes: "نعم",
  picture: "الصور",
  "without-photo": "بدون صورة",
  "one-picture": "صورة واحده ",
  "two-picture": "صورتين",
  "more-photo": "ثلاث صور او اكثر ",
  "call-id": "هوية الدعوة",
  cheerful: "مرح",
  luxury: "فخم",
  classic: "كلاسيكي",
  modern: "عصري",
  apply: "يتقدم",
  categories: "الفئات",
  "exhibition-conference": "المعارض والمؤتمرات",
  "baby-shower": "مولود جديد",
  graduation: "حفلة تخرج",
  birthday: "عيد الميلاد",
  wedding: "حفلة زفاف",
  subscription: "الاشتراكات",
  "subscription-package": "باقات الاشتراكات في مدعو",
  "customer-support": "دعم العملاء",
  contact: "جهات الإتصال",
  "request-design": "طلب تصميم",
  "current-design": "طلبات التصميم الحالية",
  "invitation-type": "نوع الدعوة",
  marriage: "زواج",
  "work-is-underway": "جاري العمل",
  "my-design": "التصاميم الخاصة بي",
  "design-request": "طلب تصميم",
  username: "أسم المستخدم",
  "order-details": "تفاصيل الطلب",
  "upload-photo": "رفع صور إن وجدت",
  "design-information": "معلومات التصميم",
  "submit-design-request": "إرسال طلب التصميم",
  "change-text-background": "تغيير النص والخلفية لبطاقتك",
  "add-invitation-details-create-import-guest-list":
    "أضف تفاصيل الدعوة ، وأنشئ قائمة مدعوين أو استوردها ، وأرسلها بضغطة زر",
  "track-rsvp": "تتبع الــ RSVPs والتواصل مع المدعوين ",
  "create-new-invitation": "إنشاء دعوة جديدة",
  "payment-problem": "مشكلة في الدفع",
  "special-design-request": "طلب تصميم خاص",
  "add-ticket": "تذكرة جديدة",
  "ticket-type": "نوع التذكرة",
  inquery: "استفسار",
  suggesation: "اقتراح",
  "technical-support": "مشكلة تقنية",
  "ticket-address": "عنوان التذكرة",
  details: "التفاصيل",
  "create-the-ticket": "إنشاء التذكرة",
  logout: "تسجيل خروج",
  "please-fill-the-otp": "من فضلك املأ otp",
  "re-set": "reset",
  riyal: "ريال",
  "subscription-now": "اشترك الآن",
  "subscription-period-month": "مدة الاشتراك بالأشهر",
  "no-of-guest-per-invitation": "عدد الضيوف لكل دعوة",
  "subscribe-to-invite": "الاشتراك في مدعو",
  "current-package": "الباقة الحالية",
  invoice: "فاتورة",
  "subscription-activation": "تفعيل الاشتراك",
  "subscription-end": "انتهاء الاشتراك",
  "credit-card": "بطاقة الائتمان",
  "new-credit-card": "بطاقة ائتمان جديدة",
  "card-number": "رقم البطاقة",
  "expiry-date": "تاريخ الانتهاء",
  cvv: "رقم الـCVV",
  "card-holder-name": "اسم حامل البطاقة",
};

const ar = {
  "browse-design": "تصفح التصاميم",
  "welcome-to-invite": "مرحبًا بك في مدعو",
  "join-the-inviter": "انضم إلى مدعـو",
  "do-you-have-account": "لديك حساب في مدعو ؟",
  "create-an-account-to-invite": "إنشاء حساب في مدعو",
  "sign-in": "تسجيل الدخول",
  "full-name": "الاسم كامل",
  or: "أو",
  email: "البريد الإلكتروني",
  phone: "رقم الجوال",
  password: "كلمة المرور الجديدة",
  cpassword: "تكرار كلمة المرور",
  "create-an-account": "إنشاء حساب",
  back: "تراجع",
  "mobile-number-activation": "تفعيل رقم الجوال",
  "to-complete-the-activation-process-please-enter-the-code":
    "لإتمام عملية التفعيل الرجاء ادخال الرمز المرسل إلى الرقم ",
  "activate-account": "تفعيل الحساب",
  "resend-the-code": "إعادة إرسال الرمز",
  "enter-mobile-or-email": "البريد الإلكتروني أو رقم الجوال",
  "pass-head": "كلمة المرور",
  "forget-your-password": "نسيت كلمة المرور",
  "enter-the-register-email": "ادخل البريد الإلكتروني المسجل في مدعو",
  submit: "إرسـال",
  "enter-the-token-you-receives": "أدخل الرمز الذي تتلقاه",
  "new-password": "كلمة المرور الجديدة",
  "design-customize": "تخصيص التصميم",
  "customize-description":
    "بإمكانك اختيار تصميم من تصاميم مدعو، وتحديث نوع الخطوط و ألوانها و أحجامها",
  "follow-up-on-invitees": "متابعة المدعوين",
  "you-can-follow-up-on-the-invitees-and-know-who-has-confirmed-their-attendance-excused-or-not-answered-the-invitation-and-other-attendance-statuses":
    "بإمكانك متابعة المدعوين ومعرفة من تم تأكيد حضوره أو عذر أو لم يرد على الدعوة وغيرها من حالات الحضور",
  "special-design-request": "طلب تصميم خاص",
  "with-the-help-of-invited-designers-you-can-stand-out-by-requesting-only-your-own-design":
    "بمساعدة مصممي مدعو بإمكانك أن تتميز عن طريق طلب تصميم خاص بك فقط",
  "start-to-invite": "ابدأ باستخدام مدعو",
  invitation: "الدعوات",
  everyone: "الجميــع",
  efective: "الفعــالة",
  archive: "المؤرشفـة",
  ended: "المنتهية",
  ongoing: "فعالة",
  for: "م ع",
  modification: "تعديل",
  type: "النوع",
  "family-font": "الحجم",
  color: "اللون",
  align: "التنسيق",
  filter: "تصفية",
  "age-group": "الفئة العمرية",
  children: "اطفال",
  youth: "شباب",
  adult: "بالغين",
  "card-with-number": "كرت مع رقم",
  no: "لا",
  yes: "نعم",
  picture: "الصور",
  "without-photo": "بدون صورة",
  "one-picture": "صورة واحده ",
  "two-picture": "صورتين",
  "more-photo": "ثلاث صور او اكثر ",
  "call-id": "هوية الدعوة",
  cheerful: "مرح",
  luxury: "فخم",
  classic: "كلاسيكي",
  modern: "عصري",
  apply: "يتقدم",
  categories: "الفئات",
  "exhibition-conference": "المعارض والمؤتمرات",
  "baby-shower": "مولود جديد",
  graduation: "حفلة تخرج",
  birthday: "عيد الميلاد",
  wedding: "حفلة زفاف",
  subscription: "الاشتراكات",
  "customer-support": "دعم العملاء",
  contact: "جهات الإتصال",
  "request-design": "طلب تصميم",
  "current-design": "طلبات التصميم الحالية",
  "invitation-type": "نوع الدعوة",
  marriage: "زواج",
  "work-is-underway": "جاري العمل",
  "my-design": "التصاميم الخاصة بي",
  username: "أسم المستخدم",
  "order-details": "تفاصيل الطلب",
  "upload-photo": "رفع صور إن وجدت",
  "design-information": "معلومات التصميم",
  "submit-design-request": "إرسال طلب التصميم",
  "change-text-background": "تغيير النص والخلفية لبطاقتك",
  "add-invitation-details-create-import-guest-list":
    "أضف تفاصيل الدعوة ، وأنشئ قائمة مدعوين أو استوردها ، وأرسلها بضغطة زر",
  "track-rsvp": "تتبع الــ RSVPs والتواصل مع المدعوين ",
  "create-new-invitation": "إنشاء دعوة جديدة",
  "payment-problem": "مشكلة في الدفع",
  "special-design-request": "طلب تصميم خاص",
  "add-ticket": "تذكرة جديدة",
  "ticket-type": "نوع التذكرة",
  inquery: "استفسار",
  suggesation: "اقتراح",
  "technical-support": "مشكلة تقنية",
  "ticket-address": "عنوان التذكرة",
  details: "التفاصيل",
  "create-the-ticket": "إنشاء التذكرة",
  logout: "تسجيل خروج",
  "please-fill-the-otp": "من فضلك املأ otp",
  "re-set": "إعادة ضبط",
  "subscription-package": "باقات الاشتراكات في مدعو",
  basic: "أساسي",
  riyal: "ريال",
  "subscription-now": "اشترك الآن",
  "subscription-period-month": "مدة الاشتراك بالأشهر",
  "no-of-guest-per-invitation": "عدد الضيوف لكل دعوة",
  "subscribe-to-invite": "الاشتراك في مدعو",
  "current-package": "الباقة الحالية",
  invoice: "فاتورة",
  "subscription-activation": "تفعيل الاشتراك",
  "subscription-end": "انتهاء الاشتراك",
  "credit-card": "بطاقة الائتمان",
  "new-credit-card": "بطاقة ائتمان جديدة",
  "card-number": "رقم البطاقة",
  "expiry-date": "تاريخ الانتهاء",
  cvv: "رقم الـCVV",
  "card-holder-name": "اسم حامل البطاقة",
};
export { en, ar };
